/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Akuseru
 */
public class ConfigWindow extends javax.swing.JFrame {

    /**
     * Creates new form ConfigWindow
     */
    public ConfigWindow() {
        initComponents();
        JTableHeader header = instructionTable.getTableHeader();
        header.setBackground(Color.GRAY);
        header.setForeground(Color.WHITE);
        header.setFont(new Font("Segoe UI",Font.BOLD,18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContinue = new javax.swing.JButton();
        txtHDD = new javax.swing.JTextField();
        txtRam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinue.setBackground(new java.awt.Color(153, 170, 181));
        btnContinue.setText("Continuar");
        btnContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnContinue.setContentAreaFilled(false);
        btnContinue.setOpaque(true);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 660, 170, 40));

        txtHDD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHDD.setText("1024");
        txtHDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHDDActionPerformed(evt);
            }
        });
        getContentPane().add(txtHDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, 100, 40));

        txtRam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRam.setText("128");
        txtRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRamActionPerformed(evt);
            }
        });
        getContentPane().add(txtRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tamaño de Disco");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tamaño de RAM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        instructionTable.setBackground(new java.awt.Color(44, 47, 51));
        instructionTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        instructionTable.setForeground(new java.awt.Color(255, 255, 255));
        instructionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"LOAD", "2"},
                {"STORE", "2"},
                {"MOV", "1"},
                {"ADD", "3"},
                {"SUB", "3"},
                {"INC", "1"},
                {"DEC", "1"},
                {"JUMP", "2"},
                {"CMP", "2"},
                {"JE/JNE", "2"},
                {"POP", "1"},
                {"PARAM", "3"}
            },
            new String [] {
                "Instruccion", "Peso"
            }
        ));
        instructionTable.setRowHeight(51);
        jScrollPane1.setViewportView(instructionTable);
        if (instructionTable.getColumnModel().getColumnCount() > 0) {
            instructionTable.getColumnModel().getColumn(0).setResizable(false);
            instructionTable.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 640));

        jLabel1.setBackground(new java.awt.Color(35, 39, 42));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        ArrayList<Integer> values = new ArrayList<Integer>();  
        try{
            for(int i =0;i<instructionTable.getRowCount();i++){
                int number = Integer.parseInt(instructionTable.getModel().getValueAt(i,1).toString());
                values.add(number);                
            }
            int memorySize = Integer.parseInt(txtRam.getText());
            int hardDSize = Integer.parseInt(txtHDD.getText());
            
            this.dispose();
            mainWindow window = new mainWindow(memorySize,hardDSize,values);
            window.setVisible(true);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ingrese numeros validos");
            }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRamActionPerformed

    private void txtHDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHDDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JTable instructionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHDD;
    private javax.swing.JTextField txtRam;
    // End of variables declaration//GEN-END:variables
}
